# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'AnyKnew' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'FMDB'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'SnapKit'
  pod 'Alamofire'
   
end
